<?php
/**
 * @file
 * Render My Logged Hours as a volunteer.
 */

define("LOG_ACTIVITY_TYPE", 66);

/**
 * Implements hook_menu().
 * This hook is adding one menu link for configuration page of this plugin.
 */
function volunteer_hours_report_menu() {

  $items = array();

  $items['admin/settings/volunteer_hours_report'] = array(
    'title' => 'Volunteer Hours Report',
    'description' => 'Manage Configuration of volunteer hours report.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('volunteer_hours_report_admin'),
    'access arguments' => array('administer onthisdate settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}


/**
 * This function is prepare one configuration form in which admin can set pagination limit.
 */
function volunteer_hours_report_admin() {
  $form = array();
  $per_page = variable_get('report_page_limit');
  if(!$per_page && empty($per_page)) {
    variable_set('report_page_limit', 10);
  }
  $form['report_page_limit'] = array(
    '#type' => 'textfield',
    '#title' => t('Page Limit'),
    '#default_value' => variable_get('report_page_limit', 10),
    '#size' => 2,
    '#description' => t("Pagination limit for Log Hours Report Block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


/**
 * Implements hook_block_info().
 * This hook is used for generating custom block from custom module.
 * This block is used for display logged hours for specific contact for any volunteer project.
 */
function volunteer_hours_report_block_info() {
  $blocks = array();
  $blocks['loghours_block'] = array(
    'info' => t('Volunteer Log Hours'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 * For generating content of block and set block parameter.
 */
function volunteer_hours_report_block_view($delta='') {
  $block = array();

  // Initialize civicrm in custom module. So we can use civicrm API in custom module.
  civicrm_initialize();
  // Get current logged in contact id from session.
  $session = CRM_Core_Session::singleton();
  $contact_id = $session->get('userID');

  switch($delta) {
    case 'loghours_block' :
      // Check user is already logged in or not.
      if($contact_id != '0' && $contact_id != NULL) {
        // disabled block subject:
        //$block['subject'] = t('My Logged Hours');

        // Prepare form with date field.
        $form = drupal_get_form('volunteer_hours_report_form');
        // Render date field and then append block result.
        $block['content'] = drupal_render($form);   
        // Generate report block content and append after search form.
        $block['content'] .= volunteer_hours_report_content($contact_id);
      }
      break;
  }

  return $block;
}

function volunteer_hours_report_default_since_date() {
  return date('Y-m-d', strtotime('-1 week'));
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a string of block content.
 */
function volunteer_hours_report_content($contact_id = "") {
  // Check if fieldmeta extension is installed or not.
  // If installed then add crmFieldMetadata module.
  $checkVolunteerExtensionEnabled = civicrm_api3('Extension', 'get', [
    'sequential' => 1,
    'full_name' => "org.civicrm.volunteer",
    'status' => "installed",
  ]);
  // If Volunteer Extension is enabled.
  if($checkVolunteerExtensionEnabled['count']) {
    // Prepare sql query for fetch ativity for specific contact.
    $select = "SELECT
    activity.subject, activity.activity_date_time, activity.duration,
    assignee.display_name as `assignee`, 
    beneficiary.display_name as `beneficiary`
    ";
    $from = " FROM civicrm_activity AS activity";
    
    // Join contacts through activity_contact table:
    // fold rows to get one-per activity:
    $join = " LEFT JOIN (SELECT 
    ac.activity_id, c.contact_id as `creator`, a.contact_id as `assignee`, t.contact_id as `target` 
    FROM civicrm_activity_contact ac 
    INNER JOIN civicrm_activity_contact a on ac.activity_id = a.activity_id AND a.record_type_id = 1 
    INNER JOIN civicrm_activity_contact t on ac.activity_id = t.activity_id AND t.record_type_id = 3 
    INNER JOIN civicrm_activity_contact c on ac.activity_id = c.activity_id AND c.record_type_id = 2 ) activity_contact on activity.id = activity_contact.activity_id
    ";
    $join .= " LEFT JOIN civicrm_contact beneficiary on activity_contact.target = beneficiary.id";
    $join .= " LEFT JOIN civicrm_contact assignee on activity_contact.assignee = assignee.id";

    // Where Condition.
    $where = " WHERE activity.activity_type_id = ". LOG_ACTIVITY_TYPE . " ";
    // Add condition for logged in user.
    if(isset($contact_id) && !empty($contact_id)) {
      $where .= " AND activity_contact.assignee = ".$contact_id;
    }
    // Get Parameters from url. If since date parameter is set add in where condition.
    $parameters = drupal_get_query_parameters();
    $today_date = date('Y-m-d', time());
    $since_date = volunteer_hours_report_default_since_date();
    if(isset($parameters['since_date']) && !empty($parameters['since_date'])) {
      $since_date = $parameters['since_date']['date'];
    }
    $where .= " AND DATE_FORMAT(activity.activity_date_time,'%Y-%m-%d')>='".$since_date."' and  DATE_FORMAT(activity.activity_date_time,'%Y-%m-%d') <= '".$today_date."'"; 

    // Order by Logic.
    $orderByColumn = "activity.id";
    $order = "ASC";

    // prepare orderby query.
    $orderby = " ORDER BY " . $orderByColumn . " " . $order;
    // Merge whole query.
    $sql = $select . $from . $join . $where . $orderby;

    $dao = new CRM_Core_DAO();
    $dao->query($sql);

    // Prepare appeal details array with proper format.
    $result = array();
    while ($dao->fetch()) {
      $htmlData = "";
      $htmlData .= "<br><b>Partner : </b>".$dao->beneficiary;
      $htmlData .= "<br><b>Subject : </b>".$dao->subject;
      $htmlData .= "<br><b>Date and Time : </b>".$dao->activity_date_time;
      $htmlData .= "<br><b>Duration : </b>".$dao->duration ." Mins";
      $result[] = $htmlData;
    }

    // Initialize the pager.
    // Get pagination limit from plugin configuration page.
    $per_page = variable_get('report_page_limit');
    if(!$per_page && empty($per_page)) {
      variable_set('report_page_limit', 10);
      $per_page = variable_get('report_page_limit');
    }
    $current_page = pager_default_initialize(count($result), $per_page);
    $paging = theme('pager');
    $chunks = array_chunk($result, $per_page, TRUE);

    // Pagination Parameters.
    $title = 'Log Hours';
    $attributes = array(
      'id' => 'log-hours',
    );
    if(isset($chunks) && !empty($chunks)) {
      // Show the appropriate items from the list
      $output = theme('item_list', array('items' =>  $chunks[$current_page], " ", '', 'attributes' => array('class' => 'node-list', 'id' => 'node_list'),));

      // Show the pager
      $output .= theme('pager', array('quantity',count($result), 'attributes' => array('class' => 'node-pager', 'id' => 'node_pager'),'element' => 0));
    } else {
      $output = "<br /><b>No records found.</b>";
    }
  }

  return $output;
}


/**
 * Implements hook_form().
 * For generating form with field in custom block.
 * Since Date field add in form.
 */
function volunteer_hours_report_form($form, &$form_submit){

  $parameters = drupal_get_query_parameters();
  $default_date = volunteer_hours_report_default_since_date();
  if(isset($parameters['since_date']) && !empty($parameters['since_date'])) {
    $default_date = date('Y-m-d', strtotime($parameters['since_date']['date']));
  }
  $form['#method'] = 'get';
  $form['since_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'Y-m-d',
    '#title' => "Since Date",
    '#required' => TRUE,
    '#default_value' => $default_date,
  );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Go'));
  $form['buttons']['reset'] = array(
    '#markup' => '<input '. drupal_attributes(array('type' => 'button', 'value' => t('Reset') )) .' id="reset_loghours_form" />',
  );

  return $form;
}